/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tracktopell.cafevisitor.view;

import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author alfredo
 */
public class FramePrincipal extends javax.swing.JFrame {

	/**
	 * Creates new form FramePrincipal
	 */
	public FramePrincipal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panels = new javax.swing.JPanel();
        panelRegistro = new PanelRegistro();
        panelBitacora = new PanelBitacora();
        panelUsuarios = new PanelUsuarios();
        panelSalida = new PanelSalida();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        registrarMenu = new javax.swing.JMenuItem();
        salidaMenu = new javax.swing.JMenuItem();
        bitacoraMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        preferenciasMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        salirMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CafeVisitor");

        panels.setLayout(new java.awt.CardLayout());

        panelRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE ENTRADA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        panels.add(panelRegistro, "panelRegistro");

        panelBitacora.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BITACORA DE REGISTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        panels.add(panelBitacora, "panelBitacora");

        panelUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USUARIOS DEL SISTEMA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        panels.add(panelUsuarios, "panelUsuarios");

        panelSalida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE SALIDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        panels.add(panelSalida, "panelSalida");

        getContentPane().add(panels, java.awt.BorderLayout.CENTER);

        archivoMenu.setText("Archivo");

        registrarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        registrarMenu.setText("Registrar Entrada");
        archivoMenu.add(registrarMenu);

        salidaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        salidaMenu.setText("Registras Salida");
        archivoMenu.add(salidaMenu);

        bitacoraMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        bitacoraMenu.setText("Bitacora");
        archivoMenu.add(bitacoraMenu);
        archivoMenu.add(jSeparator1);

        preferenciasMenu.setText("Configuración");
        archivoMenu.add(preferenciasMenu);
        archivoMenu.add(jSeparator2);

        salirMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        salirMenu.setText("Salir");
        archivoMenu.add(salirMenu);

        jMenuBar1.add(archivoMenu);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(766, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JMenuItem bitacoraMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPanel panelBitacora;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPanel panelSalida;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JPanel panels;
    private javax.swing.JMenuItem preferenciasMenu;
    private javax.swing.JMenuItem registrarMenu;
    private javax.swing.JMenuItem salidaMenu;
    private javax.swing.JMenuItem salirMenu;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the archivoMenu
	 */
	public javax.swing.JMenu getArchivoMenu() {
		return archivoMenu;
	}

	/**
	 * @return the salirMenu
	 */
	public javax.swing.JMenuItem getSalirMenu() {
		return salirMenu;
	}

	public JPanel getPanelRegistro() {
		return panelRegistro;
	}

	public JPanel getPanelBitacora() {
		return panelBitacora;
	}

	public JPanel getPanelUsuarios() {
		return panelUsuarios;
	}

	public JPanel getPanelSalida() {
		return panelSalida;
	}

	public JMenuItem getRegistrarMenu() {
		return registrarMenu;
	}

	public JMenuItem getSalidaMenu() {
		return salidaMenu;
	}

	public JMenuItem getBitacoraMenu() {
		return bitacoraMenu;
	}

	public JMenuItem getPreferenciasMenu() {
		return preferenciasMenu;
	}

	public JPanel getPanels() {
		return panels;
	}
	
}
