/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tracktopell.cafevisitor.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Softtek
 */
public class PanelSalida extends javax.swing.JPanel {

	/**
	 * Creates new form PanelRegistro
	 */
	public PanelSalida() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        folio = new javax.swing.JTextField();
        msgBusqueda = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        entrada = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        salida = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreVisitante = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        genero = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        edadAproximada = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        visitaA = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        departamento = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        restringido = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        photoPanel = new PhotoPanel();
        jPanel11 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(9, 1));

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barcode_icon_52x24.png"))); // NOI18N
        jLabel12.setText("FOLIO:");
        jLabel12.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel15.add(jLabel12);

        folio.setColumns(8);
        folio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel15.add(folio);

        msgBusqueda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        msgBusqueda.setForeground(new java.awt.Color(255, 0, 0));
        jPanel15.add(msgBusqueda);

        jPanel1.add(jPanel15);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("FECHA/HORA ENTRADA:");
        jLabel7.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel13.add(jLabel7);

        entrada.setColumns(15);
        entrada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        entrada.setEnabled(false);
        entrada.setFocusable(false);
        jPanel13.add(entrada);

        jPanel1.add(jPanel13);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("FECHA/HORA SALIDA:");
        jLabel13.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel16.add(jLabel13);

        salida.setColumns(15);
        salida.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        salida.setEnabled(false);
        salida.setFocusable(false);
        jPanel16.add(salida);

        jPanel1.add(jPanel16);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("NOMBRE VISITANTE :");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel4.add(jLabel1);

        nombreVisitante.setColumns(20);
        nombreVisitante.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombreVisitante.setEnabled(false);
        nombreVisitante.setFocusable(false);
        jPanel4.add(nombreVisitante);

        jPanel1.add(jPanel4);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("GÉNERO :");
        jLabel5.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel6.add(jLabel5);

        genero.setColumns(15);
        genero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        genero.setEnabled(false);
        genero.setFocusable(false);
        jPanel6.add(genero);

        jPanel1.add(jPanel6);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("EDAD APROXIMADA :");
        jLabel6.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel8.add(jLabel6);

        edadAproximada.setColumns(15);
        edadAproximada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        edadAproximada.setEnabled(false);
        edadAproximada.setFocusable(false);
        jPanel8.add(edadAproximada);

        jPanel1.add(jPanel8);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("VISITA A :");
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel10.add(jLabel2);

        visitaA.setColumns(25);
        visitaA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        visitaA.setEnabled(false);
        visitaA.setFocusable(false);
        jPanel10.add(visitaA);

        jPanel1.add(jPanel10);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("DEPARTAMENTO :");
        jLabel3.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel3.add(jLabel3);

        departamento.setColumns(5);
        departamento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        departamento.setEnabled(false);
        departamento.setFocusable(false);
        jPanel3.add(departamento);

        jPanel1.add(jPanel3);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("RESTRINGIDO :");
        jLabel4.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel5.add(jLabel4);

        restringido.setColumns(15);
        restringido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        restringido.setEnabled(false);
        restringido.setFocusable(false);
        jPanel5.add(restringido);

        jPanel1.add(jPanel5);

        add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTOGRAFÍA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        photoPanel.setMinimumSize(new java.awt.Dimension(100, 10));
        photoPanel.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel2.add(photoPanel, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        aceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aceptar.setText("REGISTRAR SALIDA");
        jPanel11.add(aceptar);

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelar.setText("LIMPIAR");
        jPanel11.add(cancelar);

        add(jPanel11, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

	
	public JButton getAceptar() {
		return aceptar;
	}

	public JButton getCancelar() {
		return cancelar;
	}
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField departamento;
    private javax.swing.JTextField edadAproximada;
    private javax.swing.JTextField entrada;
    private javax.swing.JTextField folio;
    private javax.swing.JTextField genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel msgBusqueda;
    private javax.swing.JTextField nombreVisitante;
    private javax.swing.JPanel photoPanel;
    private javax.swing.JTextField restringido;
    private javax.swing.JTextField salida;
    private javax.swing.JTextField visitaA;
    // End of variables declaration//GEN-END:variables


	/**
	 * @return the departamento
	 */
	public javax.swing.JTextField getDepartamento() {
		return departamento;
	}

	/**
	 * @return the edadAproximada
	 */
	public javax.swing.JTextField getEdadAproximada() {
		return edadAproximada;
	}

	/**
	 * @return the entrada
	 */
	public javax.swing.JTextField getEntrada() {
		return entrada;
	}

	/**
	 * @return the folio
	 */
	public javax.swing.JTextField getFolio() {
		return folio;
	}

	/**
	 * @return the genero
	 */
	public javax.swing.JTextField getGenero() {
		return genero;
	}


	/**
	 * @return the nombreVisitante
	 */
	public javax.swing.JTextField getNombreVisitante() {
		return nombreVisitante;
	}

	/**
	 * @return the restringido
	 */
	public javax.swing.JTextField getRestringido() {
		return restringido;
	}

	/**
	 * @return the salida
	 */
	public javax.swing.JTextField getSalida() {
		return salida;
	}

	/**
	 * @return the visitaA
	 */
	public javax.swing.JTextField getVisitaA() {
		return visitaA;
	}

	public JLabel getMsgBusqueda() {
		return msgBusqueda;
	}

	public PhotoPanel getPhotoPanel() {
		return (PhotoPanel)photoPanel;
	}
	
	
}
