INSERT INTO PREFERENCIA(ID,VALOR) VALUES ('NOMBRE_NEGOCIO','NOMBRE EDIFICIO');
INSERT INTO PREFERENCIA(ID,VALOR) VALUES ('DIRECCION_NEGOCIO','DIRECCIÓN EDIFICIO');
INSERT INTO PREFERENCIA(ID,VALOR) VALUES ('TELEFONOS_NEGOCIO','55-0000-0000,55-9999-9999');
INSERT INTO PREFERENCIA(ID,VALOR) VALUES ('EMAIL_NEGOCIO','some@mail.com');
INSERT INTO PREFERENCIA(ID,VALOR) VALUES ('PASSWORD_ADMIN','21232f297a57a5a743894a0e4a801fc3');
